
my:
  application-name: ${MY_APPLICATION_NAME:resource-server}
  hostname: ${MY_HOST_NAME:resource-server}
  port: ${MY_PORT:8080}
  client-server: ${MY_CLIENT_SERVER:http://client-server:8080}
  oauth2-server: ${MY_OAUTH2_SERVER:http://oauth2-server:8080}
  resource-server: ${MY_RESOURCE_SERVER:http://resource-server:8080}
  username: ${MY_USERNAME:forsrc}
  password: ${MY_PASSWORD:forsrc}
  eureka-server: ${MY_EUREKA_SERVER:http://forsrc:forsrc@eureka-server:8080/eureka}
  admin-server: ${MY_ADMIN_SERVER:http://admin-server:8080}
